<h1>Teste</h1><?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */

?>

<div class="charts-wrapper-dash" data-bind="scope: 'cwva_dash'" style="width: 1000px;height: 500px;margin: auto">
    <!-- ko template: getTemplate() --> <!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "chartjs": {}
        },
        ".charts-wrapper-dash": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        }
    }
</script>